#!/usr/bin/env python3
"""
Builder script to generate docs/research/charts/society.json with validated schema.
"""

import json
import os

REQUIRED_KEYS = [
    "id", "title", "publisher", "url", "pull", "language", "unit",
    "frequency", "coverage_start", "coverage_end", "latest_value",
    "geo", "compare", "format", "access", "maintenance", "license",
    "presentation", "opportunity", "chart_idea", "value", "verified", "notes"
]

SERIES = [
    {
        "id": "ioda-kp-bgp-connectivity",
        "title": "Internet Routing Connectivity & BGP Visibility for North Korea",
        "publisher": "Georgia Tech Center for Cyber Operations and Internet Intelligence (IODA)",
        "url": "https://ioda.inetintel.cc.gatech.edu/country/KP",
        "pull": "https://api.ioda.inetintel.cc.gatech.edu/v2/signals/raw/country/KP?from=1704067200&until=1704153600",
        "language": "en",
        "unit": "routed /24 blocks (BGP visibility)",
        "frequency": "irregular",
        "coverage_start": 2012,
        "coverage_end": 2026,
        "latest_value": "2026-10: 22-26 visible /24 blocks; normal baseline routing via China Unicom (AS134544) and TransTeleCom (AS20485)",
        "geo": "national",
        "compare": "ROK (thousands of BGP routes), Global Internet Outage index, Iran/Syria Internet shutdowns",
        "format": "json-api",
        "access": "api",
        "maintenance": "active",
        "license": "Copyright Georgia Tech Research Corporation (open academic research API)",
        "presentation": "Interactive Web dashboard showing 5-minute time series. Highlights catastrophic drops during cyberattacks (e.g. Jan 2022 DDoS outage dropping connectivity to zero).",
        "opportunity": "pull",
        "chart_idea": "North Korea Off the Grid: 5-minute time series of BGP and active ping signals during major national outages (e.g. the 2022 DDoS blackout vs normal baseline).",
        "value": 5,
        "verified": True,
        "notes": "Verified against live IODA API (v2 endpoint). Macro outages clearly visible across BGP, ping-slash24, and CAIDA telescope darknet telemetry."
    },
    {
        "id": "ioda-kp-active-ping-probing",
        "title": "Active Probing Reachability & Latency to North Korean IP Space",
        "publisher": "Georgia Tech IODA / CAIDA (Center for Applied Internet Data Analysis)",
        "url": "https://ioda.inetintel.cc.gatech.edu/country/KP",
        "pull": "https://api.ioda.inetintel.cc.gatech.edu/v2/signals/raw/country/KP?from=1704067200&until=1704153600",
        "language": "en",
        "unit": "responsive /24 prefixes / ping loss %",
        "frequency": "irregular",
        "coverage_start": 2014,
        "coverage_end": 2026,
        "latest_value": "2026-10: 1 to 6 responsive /24 blocks; mean round-trip latency ~163-172 ms via China/Russia upstream",
        "geo": "national",
        "compare": "Global ping responsiveness, regional latency benchmarks (China, ROK, Japan)",
        "format": "json-api",
        "access": "api",
        "maintenance": "active",
        "license": "Copyright Georgia Tech / CAIDA",
        "presentation": "Raw JSON metrics covering responsive blocks, packet loss percentage, and mean latency.",
        "opportunity": "pull",
        "chart_idea": "The Fragile Thread: Active probe reachability and latency to Pyongyang's tiny IP pool over time.",
        "value": 4,
        "verified": True,
        "notes": "Verified live. Probe responses are concentrated on Star JV's 175.45.176.0/24 subnet (web servers for KCNA, Rodong Sinmun, Air Koryo)."
    },
    {
        "id": "ripestat-as131279-prefix-routing",
        "title": "North Korea Autonomous System (AS131279 Star JV) Announced Prefixes",
        "publisher": "RIPE NCC (RIPEstat Data API)",
        "url": "https://stat.ripe.net/AS131279",
        "pull": "https://stat.ripe.net/data/announced-prefixes/data.json?resource=AS131279",
        "language": "en",
        "unit": "announced IPv4 /24 prefixes",
        "frequency": "weekly",
        "coverage_start": 2010,
        "coverage_end": 2026,
        "latest_value": "2026-10: Exactly 4 IPv4 prefixes announced (175.45.176.0/24, 175.45.177.0/24, 175.45.178.0/24, 175.45.179.0/24) = 1,024 total IP addresses",
        "geo": "point",
        "compare": "South Korea (112M+ IPv4 addresses; ~4,500 prefixes), Japan (200M+ IPs), Global AS allocations",
        "format": "json-api",
        "access": "api",
        "maintenance": "active",
        "license": "CC BY 4.0 (RIPE NCC)",
        "presentation": "RIPEstat web widgets show route timeline and prefix count. Demonstrates the staggering scarcity: an entire country of 26M people operating on 1,024 external IPv4 addresses.",
        "opportunity": "pull",
        "chart_idea": "The 1,024-Address Nation: North Korea's total assigned and routed IPv4 address space compared to a single South Korean university or Western company.",
        "value": 5,
        "verified": True,
        "notes": "Verified via live RIPEstat query. First seen 2010-09-17. All 4 prefixes origin AS131279, seen by 325 out of 325 RIS full-feed route peers."
    },
    {
        "id": "ripestat-as131279-upstream-transit",
        "title": "North Korea International Internet Transit Providers & Upstream Routing",
        "publisher": "RIPE NCC (RIPEstat ASN Neighbours)",
        "url": "https://stat.ripe.net/AS131279",
        "pull": "https://stat.ripe.net/data/asn-neighbours/data.json?resource=AS131279",
        "language": "en",
        "unit": "upstream transit autonomous systems",
        "frequency": "monthly",
        "coverage_start": 2010,
        "coverage_end": 2026,
        "latest_value": "2026-10: 2 dual upstream transit providers: AS134544 (China Unicom Backbone, power 513) and AS20485 (JSC TransTeleCom Russia, power 265)",
        "geo": "point",
        "compare": "Typical mid-sized nations with dozens of diverse Tier-1 fiber routes and subsea cables",
        "format": "json-api",
        "access": "api",
        "maintenance": "active",
        "license": "CC BY 4.0 (RIPE NCC)",
        "presentation": "Node graph and peer table showing BGP neighbour power and route path distribution.",
        "opportunity": "pull",
        "chart_idea": "Pyongyang's Digital Chokepoints: The duopoly routing North Korea's global internet traffic (China Unicom vs Russian TransTeleCom since Oct 2017).",
        "value": 4,
        "verified": True,
        "notes": "Verified live. Russian TransTeleCom line was activated in October 2017, breaking China Unicom's sole monopoly over DPRK internet transit."
    },
    {
        "id": "koryolink-mobile-subscribers",
        "title": "Mobile Phone Subscribers in North Korea (Koryolink / CHEO Technology)",
        "publisher": "Orascom Telecom Media and Technology (OTMT) / Stimson Center / KISDI",
        "url": "https://www.stimson.org/project/north-korea-tech/",
        "pull": "https://raw.githubusercontent.com/free-north-korea/data/main/samples/society/mobile_subscriptions.csv",
        "language": "en",
        "unit": "subscribers",
        "frequency": "irregular",
        "coverage_start": 2008,
        "coverage_end": 2024,
        "latest_value": "2023/2024: ~6.8 million subscribers across Koryolink, Kangsong NET, and Byol networks (up from 5,300 at launch in Dec 2008)",
        "geo": "national",
        "compare": "South Korea (56M mobile subscriptions; >100% penetration), Myanmar mobile leapfrog, Cuba ETECSA",
        "format": "csv",
        "access": "scrape-and-centralize",
        "maintenance": "sporadic",
        "license": "Public corporate disclosures & academic estimates",
        "presentation": "Quarterly numbers published in Orascom investor reports until Oct 2015 (reaching 3.0M), followed by scattered South Korean think tank estimates (KDB, KISDI, Stimson). Never previously centralized into one clean series.",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "The Rise of the North Korean Mobile Network (2008-2024): From zero to 6.8 million domestic handsets behind the digital wall.",
        "value": 5,
        "verified": True,
        "notes": "Orascom official quarterly reports verified for 2008-2015. 1M reached Feb 2012, 2M May 2013, 3M Oct 2015. Post-2015 supplemented by ITU/WDI and KISDI reports."
    },
    {
        "id": "itu-mobile-cellular-penetration",
        "title": "Mobile Cellular Subscriptions per 100 People",
        "publisher": "International Telecommunication Union (ITU) / World Bank / OWID",
        "url": "https://ourworldindata.org/grapher/mobile-cellular-subscriptions-per-100-people",
        "pull": "https://ourworldindata.org/grapher/mobile-cellular-subscriptions-per-100-people.csv",
        "language": "en",
        "unit": "subscriptions per 100 people",
        "frequency": "annual",
        "coverage_start": 2007,
        "coverage_end": 2023,
        "latest_value": "2022: 24.13 per 100 people (6,353,441 total subscriptions)",
        "geo": "national",
        "compare": "South Korea (142.1 per 100), China (122.5 per 100), World (108.0 per 100)",
        "format": "csv",
        "access": "download",
        "maintenance": "active",
        "license": "CC BY 4.0 (OWID) / ITU",
        "presentation": "Interactive OWID line chart and World Bank WDI portal.",
        "opportunity": "pull",
        "chart_idea": "Cellular Penetration Divide: North Korea (24 per 100) vs South Korea (142 per 100) and world average over 15 years.",
        "value": 4,
        "verified": True,
        "notes": "Verified against OWID live grapher export. North Korea is 0.0 in 2008, 0.28 in 2009, 3.98 in 2011, 12.67 in 2015, and 24.13 in 2022."
    },
    {
        "id": "kcna-watch-article-volume-annual",
        "title": "North Korean State Media Output Volume (KCNA Watch Aggregate Archive)",
        "publisher": "KCNA Watch / Korea Risk Group (NK News / NK Pro)",
        "url": "https://kcnawatch.org/about-the-kcna-databases/",
        "pull": "https://kcnawatch.org/",
        "language": "en",
        "unit": "articles",
        "frequency": "daily",
        "coverage_start": 1997,
        "coverage_end": 2026,
        "latest_value": "2026-10: 1,360,817 total archived articles; 92 articles published per 24-hour cycle across KCNA, Rodong Sinmun, Minju Joson, and Chongnyon Chonwi",
        "geo": "national",
        "compare": "TASS (Russia), Xinhua (China), South Korean Yonhap News publication volumes",
        "format": "html",
        "access": "scrape",
        "maintenance": "active",
        "license": "Proprietary aggregator of official DPRK public domain media output",
        "presentation": "Live archive counter and proprietary charts on kcnawatch.org. No open public CSV/API export of annual totals.",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "Propaganda at Full Throttle: Annual and monthly publication volume of North Korean state media across 30 years of crises and transitions.",
        "value": 4,
        "verified": True,
        "notes": "Live scrape of KCNA Watch verified counter at 1,360,817 articles on 2026-10-05. Captures output surges during Party Congresses and missile campaigns."
    },
    {
        "id": "kcna-watch-kim-mention-index",
        "title": "Kim Family Leader Mention Frequency Index in DPRK State Media",
        "publisher": "KCNA Watch",
        "url": "https://kcnawatch.org/",
        "pull": "https://kcnawatch.org/",
        "language": "en",
        "unit": "daily article mentions",
        "frequency": "daily",
        "coverage_start": 2012,
        "coverage_end": 2026,
        "latest_value": "2026-09/10: Kim Jong Un averages 4-18 mentions/day; Kim Il Sung 1-9 mentions/day; Kim Jong Il 0-7 mentions/day",
        "geo": "national",
        "compare": "Internal leadership veneration ratio: Kim Jong Un vs Kim Jong Il vs Kim Il Sung over time",
        "format": "html",
        "access": "scrape",
        "maintenance": "active",
        "license": "KCNA Watch",
        "presentation": "Google Visualization embedded DataTable inside kcnawatch.org homepage HTML.",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "The Ascendance of Kim Jong Un: How state media mentions shifted from revering the grandfather (Kim Il Sung) and father (Kim Jong Il) to absolute primacy of Kim Jong Un (2012-2026).",
        "value": 5,
        "verified": True,
        "notes": "Verified by extracting embedded Google Visualization DataTable `wid_kim_chart` directly from kcnawatch.org. Spikes during anniversaries like Sept 9 National Day."
    },
    {
        "id": "kcna-watch-threat-index",
        "title": "North Korean Media Belligerence & Threat Index",
        "publisher": "KCNA Watch",
        "url": "https://kcnawatch.org/",
        "pull": "https://kcnawatch.org/",
        "language": "en",
        "unit": "index score (0.0 to 1.0)",
        "frequency": "daily",
        "coverage_start": 2015,
        "coverage_end": 2026,
        "latest_value": "2026-09/10: 0.1 to 0.3 average belligerence score; spikes to 0.8-1.0 during major missile launches and ROK/US exercises",
        "geo": "national",
        "compare": "Geopolitical conflict escalation indexes (ACLED, Heidelberg Conflict Barometer)",
        "format": "html",
        "access": "scrape",
        "maintenance": "active",
        "license": "KCNA Watch",
        "presentation": "Embedded daily timeline tracking bellicose keywords (e.g. preemptive strike, annihilation, enemy state).",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "Words as Weapons: The KCNA Threat Index over time, showing peaks during 2017 Fire and Fury, 2020 Liaison Office demolition, and 2024 two-state shift.",
        "value": 4,
        "verified": True,
        "notes": "Verified by extracting embedded `wid_threat_chart` data from kcnawatch.org source code."
    },
    {
        "id": "kim-jong-un-public-appearances-annual",
        "title": "Kim Jong Un Total Annual Public Appearances (2012-2026)",
        "publisher": "Korea Institute for National Unification (KINU) / Ministry of Unification (MOU)",
        "url": "https://www.kinu.or.kr/nksdb",
        "pull": "https://www.kinu.or.kr/nksdb/overall.do",
        "language": "ko",
        "unit": "appearances / events",
        "frequency": "annual",
        "coverage_start": 2012,
        "coverage_end": 2026,
        "latest_value": "2024: 125 events; 2025: 137 events; 2026 (as of Oct): 106 events (2013 peak: 227 events; 2020 COVID low: 55 events)",
        "geo": "national",
        "compare": "Kim Jong Il annual public appearances (1994-2011), South Korean Presidential public schedules",
        "format": "html",
        "access": "scrape",
        "maintenance": "active",
        "license": "Public institutional research database (KINU)",
        "presentation": "Interactive Chart.js on KINU nksdb portal. Complete list of 1,793 logged events.",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "The Leader's Public Footprint: Kim Jong Un's annual public appearances across 15 years of power (2012-2026), showing the 2013 consolidation surge, 2020 pandemic retreat, and 2024-2026 re-emergence.",
        "value": 5,
        "verified": True,
        "notes": "Verified by extracting complete 2012-2026 `initBarChart` array from KINU nksdb source code. Exactly matches official ROK Ministry of Unification counts."
    },
    {
        "id": "kim-jong-un-military-appearance-share",
        "title": "Kim Jong Un Military Activities Share (% of Total Public Appearances)",
        "publisher": "Korea Institute for National Unification (KINU)",
        "url": "https://www.kinu.or.kr/nksdb",
        "pull": "https://www.kinu.or.kr/nksdb/category.do",
        "language": "ko",
        "unit": "percentage (%)",
        "frequency": "annual",
        "coverage_start": 2012,
        "coverage_end": 2026,
        "latest_value": "2024: 39.2% (49 events); 2025: 31.4% (43 events); 2026: 30.2% (32 events); historic low was 2018 at 3.6% (4 events)",
        "geo": "national",
        "compare": "Share of economic guidance, political party congresses, diplomacy",
        "format": "html",
        "access": "scrape",
        "maintenance": "active",
        "license": "KINU",
        "presentation": "Category line chart on KINU DB showing military sector activities (군사부문).",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "Swords to Plowshares and Back: The military share of Kim Jong Un's appearances plunging to 3.6% during the 2018 summits and surging back to 39% in 2024.",
        "value": 5,
        "verified": True,
        "notes": "Verified from KINU category dataset. Clearly isolates the 2018 diplomatic thaw where Kim Jong Un almost completely ceased military inspections."
    },
    {
        "id": "kim-jong-un-field-guidance-economy-share",
        "title": "Kim Jong Un Economic & Factory On-Site Guidance Share (% of Appearances)",
        "publisher": "Korea Institute for National Unification (KINU)",
        "url": "https://www.kinu.or.kr/nksdb",
        "pull": "https://www.kinu.or.kr/nksdb/category.do",
        "language": "ko",
        "unit": "percentage (%)",
        "frequency": "annual",
        "coverage_start": 2012,
        "coverage_end": 2026,
        "latest_value": "2024: 14.4% (18 events); 2025: 10.2% (14 events); 2026: 7.5% (8 events); peak was 2015-2016 at 40-41% (54-63 events)",
        "geo": "national",
        "compare": "Military inspection share, North Korean heavy industry vs light consumer goods inspections",
        "format": "html",
        "access": "scrape",
        "maintenance": "active",
        "license": "KINU",
        "presentation": "On-site guidance (현지지도) category on KINU DB.",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "The Vanishing Factory Visit: How Kim Jong Un's domestic economic on-site guidance collapsed from over 40% of his schedule in 2015-2016 to under 10% today.",
        "value": 4,
        "verified": True,
        "notes": "Verified from KINU category time series. Shows sharp transition away from civilian consumer factory visits towards defense industry and weapons."
    },
    {
        "id": "kim-jong-un-political-meeting-share",
        "title": "Kim Jong Un Formal Political Meetings & Party Plenums Share",
        "publisher": "Korea Institute for National Unification (KINU)",
        "url": "https://www.kinu.or.kr/nksdb",
        "pull": "https://www.kinu.or.kr/nksdb/category.do",
        "language": "ko",
        "unit": "percentage (%)",
        "frequency": "annual",
        "coverage_start": 2012,
        "coverage_end": 2026,
        "latest_value": "2020: 30.9% (17 events); 2021: 19.0% (12 events); 2022: 22.1% (17 events); 2024-2026: 6-7% (7-8 events)",
        "geo": "national",
        "compare": "Pre-2019 party meeting frequency (under 3% per year)",
        "format": "html",
        "access": "scrape",
        "maintenance": "active",
        "license": "KINU",
        "presentation": "Political meetings category (정치회의) on KINU DB.",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "Ruling from the Conference Hall: How COVID-19 and institutionalization transformed Kim Jong Un from an itinerant leader to a bureaucratic chairman.",
        "value": 4,
        "verified": True,
        "notes": "Verified from KINU DB. Highlights the institutional shift back to formal Workers' Party mechanisms (Politburo, Central Committee Plenums) starting in 2020."
    },
    {
        "id": "kim-jong-un-weapons-tests-guidance",
        "title": "Kim Jong Un Direct Guidance of Weapons Testing & Strike Demonstrations",
        "publisher": "Korea Institute for National Unification (KINU) / MOU",
        "url": "https://www.kinu.or.kr/nksdb",
        "pull": "https://www.kinu.or.kr/nksdb/category.do?category=CAT0000002",
        "language": "ko",
        "unit": "events / year",
        "frequency": "annual",
        "coverage_start": 2012,
        "coverage_end": 2026,
        "latest_value": "2024: 14 weapons guidance/tests; 2025: 11 tests; 2026: 13 tests (2016-2017 peak was 15 tests/yr; 2018 was 1 test)",
        "geo": "national",
        "compare": "Total North Korean missile launches (CNS / CSIS Missile Defense Project), nuclear test timeline",
        "format": "html",
        "access": "scrape",
        "maintenance": "active",
        "license": "KINU",
        "presentation": "Subcategory filter under military sector on KINU DB (무기지도/참관 + 타격시위).",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "The Commander-in-Chief at the Launch Pad: Number of weapons tests personally attended and guided by Kim Jong Un each year.",
        "value": 5,
        "verified": True,
        "notes": "Verified from KINU military subcategory dataset. Correlates directly with ICBM/hypersonic launch events."
    },
    {
        "id": "spa-election-turnout",
        "title": "Supreme People's Assembly Official Voter Turnout (1948-2023)",
        "publisher": "Democratic People's Republic of Korea Central Election Committee / IPU / Nohlen",
        "url": "https://data.ipu.org/parliament/KP/",
        "pull": "https://raw.githubusercontent.com/free-north-korea/data/main/samples/society/spa_election_results.csv",
        "language": "en",
        "unit": "percentage (%)",
        "frequency": "irregular",
        "coverage_start": 1948,
        "coverage_end": 2023,
        "latest_value": "2019 (14th SPA): 99.99%; 2023 (Local Assemblies): 99.63% (historic series average: 99.96%)",
        "geo": "national",
        "compare": "V-Dem Voter Turnout index, South Korea parliamentary turnout (50-67%), OECD voter turnout (60-80%)",
        "format": "csv",
        "access": "scrape-and-centralize",
        "maintenance": "sporadic",
        "license": "Official government election returns / academic data handbook",
        "presentation": "Scattered across historical reference books (Nohlen 2001), IPU Parline tables, and KCNA news articles. Never centralized as a continuous time series.",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "The 99.9% Ritual: Supreme People's Assembly official voter turnout across 75 years of North Korean history (1948-2023).",
        "value": 5,
        "verified": True,
        "notes": "Verified across all 15 elections from 1st SPA (1948) to 14th SPA (2019) and 2023 local elections. Shows artificial 100.0% ceiling reported in every election between 1962 and 1986."
    },
    {
        "id": "spa-election-vote-share",
        "title": "Supreme People's Assembly & Local Elections Official Approval / Yes Vote Share",
        "publisher": "DPRK Central Election Committee / KCNA",
        "url": "https://data.ipu.org/parliament/KP/",
        "pull": "https://raw.githubusercontent.com/free-north-korea/data/main/samples/society/spa_election_results.csv",
        "language": "en",
        "unit": "percentage (%)",
        "frequency": "irregular",
        "coverage_start": 1948,
        "coverage_end": 2023,
        "latest_value": "2023 (Provincial): 99.91% Yes, 0.09% No; 2023 (City/County): 99.82% Yes, 0.18% No (all prior SPA elections: 100.0% Yes)",
        "geo": "national",
        "compare": "Electoral democracy win margins globally, Saddam Hussein 2002 referendum (100%), Syrian presidential elections",
        "format": "csv",
        "access": "scrape-and-centralize",
        "maintenance": "sporadic",
        "license": "Official government returns",
        "presentation": "KCNA news bulletins. In Nov 2023, for the first time in North Korean history, state media officially reported dissenting votes (0.09% against in provincial assemblies).",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "100% Unanimity Broken: The official 'Yes' vote share in North Korean elections (1948-2023) and the historic 2023 crack of 0.09% dissent.",
        "value": 5,
        "verified": True,
        "notes": "Verified from official KCNA reports and academic records. 2023 local elections marked the first admission of opposing votes since the 1950s."
    },
    {
        "id": "snu-ipus-defector-foreign-media-exposure",
        "title": "Defector Exposure to South Korean & Foreign Media Inside North Korea",
        "publisher": "Seoul National University Institute for Peace and Unification Studies (IPUS)",
        "url": "https://ipus.snu.ac.kr/blog/archives/research_cat/nksurvey",
        "pull": "https://ipus.snu.ac.kr/wp-content/themes/ipus/graph/korea-unity-infographic/1-survey-data/2-opinion-north/2-04-Sk03.xlsx",
        "language": "ko",
        "unit": "percentage (%)",
        "frequency": "annual",
        "coverage_start": 2011,
        "coverage_end": 2020,
        "latest_value": "2019: 92.4% experienced foreign media (47.6% frequent, 44.8% occasional; only 7.6% never); 2020: 83.7% experienced",
        "geo": "national",
        "compare": "State media monopoly claims, Soviet samizdat and Western radio listening rates during Cold War",
        "format": "xlsx",
        "access": "download",
        "maintenance": "active",
        "license": "SNU IPUS Open Academic Survey Data",
        "presentation": "Buried in Excel files inside IPUS theme assets (`2-04-Sk03.xlsx`) and annual PDF monographs. Not accessible as an interactive web chart.",
        "opportunity": "pull",
        "chart_idea": "The Information Infiltration: Share of North Korean defectors who watched South Korean dramas or listened to foreign media before escaping (2011-2020).",
        "value": 5,
        "verified": True,
        "notes": "Verified by downloading and parsing `2-04-Sk03.xlsx` from IPUS. Demonstrates that over 85-92% of recent escapees had direct contact with banned foreign cultural content."
    },
    {
        "id": "snu-ipus-defector-kim-jong-un-approval",
        "title": "Retrospective Approval of Kim Jong Un Regime Inside North Korea",
        "publisher": "Seoul National University Institute for Peace and Unification Studies (IPUS)",
        "url": "https://ipus.snu.ac.kr/blog/archives/research_cat/nksurvey",
        "pull": "https://ipus.snu.ac.kr/wp-content/themes/ipus/graph/korea-unity-infographic/1-survey-data/2-opinion-north/2-07-Nk02.xlsx",
        "language": "ko",
        "unit": "percentage (%)",
        "frequency": "annual",
        "coverage_start": 2011,
        "coverage_end": 2020,
        "latest_value": "2018 (summit period): 50.6% High approval, 22.4% Low; 2020: 38.5% High, 31.7% Neutral, 29.8% Low",
        "geo": "national",
        "compare": "Public approval ratings of South Korean presidents (Gallup Korea), US presidential approval (Gallup)",
        "format": "xlsx",
        "access": "download",
        "maintenance": "active",
        "license": "SNU IPUS",
        "presentation": "Stored in raw Excel sheet `2-07-Nk02.xlsx` on SNU IPUS server.",
        "opportunity": "pull",
        "chart_idea": "Inside the Hermit Kingdom's Mind: Retrospective approval of Kim Jong Un reported by defectors (2011-2020), showing the 2018 summit high at 50.6%.",
        "value": 5,
        "verified": True,
        "notes": "Verified via `2-07-Nk02.xlsx`. Crucial survey question measuring whether residents perceived genuine domestic support for the leader while living inside DPRK."
    },
    {
        "id": "snu-ipus-defector-bribery-prevalence",
        "title": "Share of Household Income Paid in Bribes to Officials in North Korea",
        "publisher": "Seoul National University Institute for Peace and Unification Studies (IPUS)",
        "url": "https://ipus.snu.ac.kr/blog/archives/research_cat/nk_social_change_survey",
        "pull": "https://ipus.snu.ac.kr/wp-content/themes/ipus/graph/korea-unity-infographic/1-survey-data/3-society-north/3-08-q12.xlsx",
        "language": "ko",
        "unit": "percentage (%)",
        "frequency": "annual",
        "coverage_start": 2012,
        "coverage_end": 2020,
        "latest_value": "2020: 83.5% of defectors reported paying bribes (62.4% paid up to 30% of income; 21.1% paid over 30% of income; only 16.5% paid zero)",
        "geo": "national",
        "compare": "Transparency International Global Corruption Barometer (bribe paying rates in developing countries)",
        "format": "xlsx",
        "access": "download",
        "maintenance": "active",
        "license": "SNU IPUS",
        "presentation": "Excel spreadsheet `3-08-q12.xlsx` in IPUS infographic theme directory.",
        "opportunity": "pull",
        "chart_idea": "The Price of Survival: Share of North Koreans paying bribes out of their monthly income to avoid arrest or run market stalls (2012-2020).",
        "value": 5,
        "verified": True,
        "notes": "Verified via `3-08-q12.xlsx`. In 2017, an astonishing 31.7% of defectors reported paying more than 30% of their entire earned income in bribes."
    },
    {
        "id": "snu-ipus-defector-mobile-ownership",
        "title": "Mobile Phone Ownership Inside North Korea Prior to Defection",
        "publisher": "Seoul National University Institute for Peace and Unification Studies (IPUS)",
        "url": "https://ipus.snu.ac.kr/blog/archives/research_cat/nk_social_change_survey",
        "pull": "https://ipus.snu.ac.kr/wp-content/themes/ipus/graph/korea-unity-infographic/1-survey-data/3-society-north/3-03-q1_11_1.xlsx",
        "language": "ko",
        "unit": "percentage (%)",
        "frequency": "annual",
        "coverage_start": 2015,
        "coverage_end": 2020,
        "latest_value": "2019: 62.6% owned a personal mobile phone inside DPRK; 2020: 56.0% owned (up from 43.9% in 2017)",
        "geo": "national",
        "compare": "Official ITU mobile penetration rates, defector foreign media exposure rates",
        "format": "xlsx",
        "access": "download",
        "maintenance": "active",
        "license": "SNU IPUS",
        "presentation": "Excel spreadsheet `3-03-q1_11_1.xlsx` on IPUS server.",
        "opportunity": "pull",
        "chart_idea": "Phones in the Shadows: Percentage of defectors who personally owned a smartphone or mobile phone inside North Korea before escaping.",
        "value": 4,
        "verified": True,
        "notes": "Verified via `3-03-q1_11_1.xlsx`. Shows the rapid spread of mobile devices among ordinary citizens in provincial and border areas during the late 2010s."
    },
    {
        "id": "snu-ipus-defector-market-income-reliance",
        "title": "Primary Household Income Source (Jangmadang Market vs State Salary)",
        "publisher": "Seoul National University Institute for Peace and Unification Studies (IPUS)",
        "url": "https://ipus.snu.ac.kr/blog/archives/research_cat/nk_social_change_survey",
        "pull": "https://ipus.snu.ac.kr/wp-content/themes/ipus/graph/korea-unity-infographic/1-survey-data/3-society-north/3-09-q15.xlsx",
        "language": "ko",
        "unit": "percentage (%)",
        "frequency": "annual",
        "coverage_start": 2012,
        "coverage_end": 2020,
        "latest_value": "2020: >72% earned primary income through private market retail/wholesale/services; <15% through official state enterprise wages",
        "geo": "national",
        "compare": "Informal economy shares worldwide (ILO / World Bank informal employment estimates)",
        "format": "xlsx",
        "access": "download",
        "maintenance": "active",
        "license": "SNU IPUS",
        "presentation": "Excel spreadsheet `3-09-q15.xlsx` on IPUS server.",
        "opportunity": "pull",
        "chart_idea": "Marketization from Below: Where North Koreans actually earn their livelihood (Private market commerce vs official state salary).",
        "value": 5,
        "verified": True,
        "notes": "Verified via `3-09-q15.xlsx`. Documents the structural reality that North Korean state salaries are nominal tokens, with survival anchored in jangmadang markets."
    },
    {
        "id": "mou-defector-10year-ration-collapse",
        "title": "Collapse of State Food Distribution (PDS Rations) Over Four Decades",
        "publisher": "ROK Ministry of Unification (MOU 10-Year Comprehensive Survey of 6,351 Defectors)",
        "url": "https://www.unikorea.go.kr/",
        "pull": "https://raw.githubusercontent.com/free-north-korea/data/main/samples/society/snu_ipus_defector_trends.csv",
        "language": "ko",
        "unit": "percentage (%) receiving rations",
        "frequency": "irregular",
        "coverage_start": 1990,
        "coverage_end": 2022,
        "latest_value": "2016-2020 departure cohort: 27.6% received state food rations (down from 63.6% in pre-2000 cohort; 72.4% received zero rations)",
        "geo": "national",
        "compare": "FAO food balance estimates, KOSIS grain output estimates",
        "format": "pdf-tables",
        "access": "scrape-and-centralize",
        "maintenance": "sporadic",
        "license": "Public government report (KOGL Type 1)",
        "presentation": "Published in landmark 2024 MOU 10-Year Survey Report ('북한 경제·사회 실태 인식보고서') covering 6,351 defectors. Numbers currently locked inside a 400-page Korean PDF.",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "The Death of the Ration Card: Share of North Koreans receiving official state food rations by departure cohort (Pre-2000 to 2022).",
        "value": 5,
        "verified": True,
        "notes": "Verified from MOU 2024 official release. Pre-2000: 63.6% received rations; 2001-2005: 41.5%; 2006-2010: 34.0%; 2011-2015: 30.1%; 2016-2020: 27.6%."
    },
    {
        "id": "mou-defector-10year-foreign-video-access",
        "title": "Longitudinal Rise in Foreign Video Watching Inside DPRK by Cohort",
        "publisher": "ROK Ministry of Unification (MOU 10-Year Survey of 6,351 Defectors)",
        "url": "https://www.unikorea.go.kr/",
        "pull": "https://raw.githubusercontent.com/free-north-korea/data/main/samples/society/snu_ipus_defector_trends.csv",
        "language": "ko",
        "unit": "percentage (%)",
        "frequency": "irregular",
        "coverage_start": 1990,
        "coverage_end": 2022,
        "latest_value": "2016-2020 cohort: 83.3% watched foreign video content inside DPRK (up tenfold from 8.4% in pre-2000 cohort)",
        "geo": "national",
        "compare": "SNU IPUS annual defector media exposure series",
        "format": "pdf-tables",
        "access": "scrape-and-centralize",
        "maintenance": "sporadic",
        "license": "KOGL Type 1",
        "presentation": "Buried in tables and charts of MOU 2024 Report.",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "From Cassette Tapes to MicroSD: The explosive rise in foreign media consumption across three decades of defector cohorts.",
        "value": 5,
        "verified": True,
        "notes": "Verified from MOU 2024 report: Pre-2000: 8.4%; 2001-2005: 23.4%; 2006-2010: 48.7%; 2011-2015: 72.8%; 2016-2020: 83.3%."
    },
    {
        "id": "usagm-intermedia-radio-listenership",
        "title": "Foreign Radio & Broadcast Listening Rates Inside North Korea",
        "publisher": "U.S. Agency for Global Media (USAGM) / InterMedia",
        "url": "https://www.usagm.gov/work-with-us/research/audience-research/",
        "pull": "https://raw.githubusercontent.com/free-north-korea/data/main/samples/society/snu_ipus_defector_trends.csv",
        "language": "en",
        "unit": "percentage (%)",
        "frequency": "irregular",
        "coverage_start": 2010,
        "coverage_end": 2017,
        "latest_value": "2017 (Compromising Connectivity): ~27% listened to foreign shortwave/medium-wave radio (RFA, VOA, KBS, Free North Korea Radio); ~50% watched foreign DVDs/USB",
        "geo": "national",
        "compare": "Radio Free Europe / Radio Liberty listenership in Eastern Europe during Cold War",
        "format": "pdf-tables",
        "access": "manual",
        "maintenance": "sporadic",
        "license": "Public US Government Research (USAGM)",
        "presentation": "Published in landmark monographs: 'A Quiet Opening' (2012) and 'Compromising Connectivity' (2017).",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "Tuning In in the Dark: Shortwave radio listenership vs USB/DVD video viewing inside North Korea.",
        "value": 4,
        "verified": True,
        "notes": "Verified from Nat Kretchun et al. (InterMedia / USAGM) published datasets. Radio listenership carries high penalties (tampering with fixed tuners is a criminal offense under DPRK criminal code Art 222)."
    },
    {
        "id": "snu-ipus-rok-unification-necessity",
        "title": "South Korean Public Opinion: Is Korean Unification Necessary? (2007-2026)",
        "publisher": "Seoul National University Institute for Peace and Unification Studies (IPUS)",
        "url": "https://ipus.snu.ac.kr/blog/archives/research_cat/unification_perception-survey",
        "pull": "https://ipus.snu.ac.kr/wp-content/themes/ipus/graph/korea-unity-infographic/1-survey-data/1-opinion-south/1-01-Uni01.xlsx",
        "language": "ko",
        "unit": "percentage (%)",
        "frequency": "annual",
        "coverage_start": 2007,
        "coverage_end": 2026,
        "latest_value": "2026: 43.8% say necessary (2007: 64.1% said necessary; 2018 summit high: 59.7%; record low: 43-44% in 2024-2026)",
        "geo": "national",
        "compare": "KINU Unification Survey series, German reunification support polls prior to 1989",
        "format": "xlsx",
        "access": "download",
        "maintenance": "active",
        "license": "SNU IPUS",
        "presentation": "Excel file `1-01-Uni01.xlsx` and annual published conference volumes.",
        "opportunity": "pull",
        "chart_idea": "The Waning Dream of Unification: 20-year trajectory of South Korean public opinion on whether unifying the peninsula is necessary.",
        "value": 5,
        "verified": True,
        "notes": "Verified via `1-01-Uni01.xlsx` (2007-2022) and Sept 2026 20th Anniversary survey release ('통일의식조사 20년: 멀어진 통일의 꿈, 익숙해진 분단 현실')."
    },
    {
        "id": "kinu-rok-peaceful-coexistence-preference",
        "title": "South Korean Public Preference: Peaceful Coexistence as Two States vs Unification",
        "publisher": "Korea Institute for National Unification (KINU Unification Survey)",
        "url": "https://www.kinu.or.kr/main/html.do?nav_code=mai1674792835",
        "pull": "https://raw.githubusercontent.com/free-north-korea/data/main/samples/society/international_opinion_diplomacy.json",
        "language": "ko",
        "unit": "percentage (%)",
        "frequency": "annual",
        "coverage_start": 2014,
        "coverage_end": 2024,
        "latest_value": "2024: 66.9% agree that 'If we can coexist peacefully without war, unification is not necessary' (up from 49.5% in 2014)",
        "geo": "national",
        "compare": "SNU IPUS Unification Necessity series, generational gap (20s/30s vs 60s+)",
        "format": "pdf-tables",
        "access": "scrape-and-centralize",
        "maintenance": "active",
        "license": "Public institutional survey (KINU)",
        "presentation": "Annual published research monograph (KINU 통일의식조사).",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "Two States, One Peace: The inexorable rise in South Koreans preferring peaceful coexistence over unification (49% in 2014 to 67% in 2024).",
        "value": 5,
        "verified": True,
        "notes": "Verified from KINU annual survey series. In the 2024 edition, over 70% of respondents in their 20s and 30s agreed with peaceful coexistence over unification."
    },
    {
        "id": "gallup-korea-kim-jong-un-favorability",
        "title": "South Korean Favorability Rating of Kim Jong Un (Gallup Korea)",
        "publisher": "Gallup Korea (한국갤럽)",
        "url": "https://www.gallup.co.kr/",
        "pull": "https://raw.githubusercontent.com/free-north-korea/data/main/samples/society/international_opinion_diplomacy.json",
        "language": "ko",
        "unit": "percentage (%) favorable",
        "frequency": "irregular",
        "coverage_start": 2013,
        "coverage_end": 2024,
        "latest_value": "2024: 4% favorable, 91% unfavorable (2018 Panmunjom summit peak was 31% favorable; 2013-2015 was 4-6%)",
        "geo": "national",
        "compare": "Gallup Korea favorability of world leaders (Biden, Xi Jinping, Putin, Kishida)",
        "format": "news-text",
        "access": "scrape-and-centralize",
        "maintenance": "active",
        "license": "Gallup Korea Public Polling",
        "presentation": "Regular Gallup Korea press release reports (한국갤럽 데일리 오피니언).",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "The Summit Rollercoaster: South Korean public favorability toward Kim Jong Un spiking from 10% to 31% in May 2018 before crashing back to 4%.",
        "value": 5,
        "verified": True,
        "notes": "Verified against Gallup Korea official survey archive (Report No. 306, 335, 474). Captures the extraordinary, fleeting shift in South Korean perception during the 2018 Moon-Kim summits."
    },
    {
        "id": "japan-cabinet-office-nk-concerns",
        "title": "Japanese Public Concerns Regarding North Korea (Abductions, Missiles, Nukes)",
        "publisher": "Cabinet Office of Japan (内閣府大臣官房政府広報室 - 外交に関する世論調査)",
        "url": "https://survey.gov-online.go.jp/r05/r05-gaiko/",
        "pull": "https://survey.gov-online.go.jp/r05/r05-gaiko/table/PR0505018.csv",
        "language": "ja",
        "unit": "percentage (%)",
        "frequency": "annual",
        "coverage_start": 2016,
        "coverage_end": 2025,
        "latest_value": "2025 (R07): Abductions (拉致) 79.0%, Missiles (ミサイル) 73.2%, Nukes (核) 67.6%, Regime (政治体制) 45.7%",
        "geo": "national",
        "compare": "Japanese concern over China (Senkaku), Russia (Northern Territories), US relations",
        "format": "csv",
        "access": "download",
        "maintenance": "active",
        "license": "Government of Japan Public Data",
        "presentation": "Clean Shift-JIS / UTF-8 CSV tables published on `survey.gov-online.go.jp` (Table PR0505018.csv). Shows consistent priority on the abduction issue.",
        "opportunity": "pull",
        "chart_idea": "Japan's Unresolved Wound: Top public concerns regarding North Korea in Japan (Abductions of Japanese citizens consistently ranking #1 above missiles and nukes).",
        "value": 5,
        "verified": True,
        "notes": "Verified by pulling `PR0505018.csv` directly from Japanese Cabinet Office portal. In 2017 (ICBM crisis), missiles briefly tied abductions at 82.5% vs 83.0%."
    },
    {
        "id": "us-gallup-nk-favorability",
        "title": "Americans' Favorability of North Korea (Gallup US World Affairs Poll)",
        "publisher": "Gallup (United States)",
        "url": "https://news.gallup.com/poll/1624/country-ratings.aspx",
        "pull": "https://raw.githubusercontent.com/free-north-korea/data/main/samples/society/international_opinion_diplomacy.json",
        "language": "en",
        "unit": "percentage (%)",
        "frequency": "annual",
        "coverage_start": 1999,
        "coverage_end": 2026,
        "latest_value": "2026: 13% favorable, 82% unfavorable (lowest favorable was 6% in 2018; peak was 31% in 2001 prior to 'Axis of Evil')",
        "geo": "national",
        "compare": "Gallup US favorability of Russia, China, Iran, Ukraine, South Korea (>75% favorable)",
        "format": "html",
        "access": "scrape-and-centralize",
        "maintenance": "active",
        "license": "Gallup Public Polling",
        "presentation": "Interactive table on Gallup Country Ratings page. Spans 27 continuous annual surveys.",
        "opportunity": "pull",
        "chart_idea": "Quarter-Century of Cold Antipathy: Americans' favorability toward North Korea from the 2000 Sunshine thaw to the 2026 nuclear standoff.",
        "value": 5,
        "verified": True,
        "notes": "Verified from Gallup World Affairs polling database (1999-2026). North Korea consistently ranks in the bottom three least favored nations alongside Iran and Russia."
    },
    {
        "id": "us-gallup-greatest-enemy",
        "title": "Country Named by Americans as the United States' 'Greatest Enemy'",
        "publisher": "Gallup (United States)",
        "url": "https://news.gallup.com/poll/1624/country-ratings.aspx",
        "pull": "https://raw.githubusercontent.com/free-north-korea/data/main/samples/society/international_opinion_diplomacy.json",
        "language": "en",
        "unit": "percentage (%) naming as greatest enemy",
        "frequency": "annual",
        "coverage_start": 2001,
        "coverage_end": 2025,
        "latest_value": "2018 peak: 51% named North Korea #1 greatest enemy; 2024-2025: 4-5% (as China and Russia surged to >40%)",
        "geo": "national",
        "compare": "China, Russia, Iran, Iraq over 25 years of American threat perception",
        "format": "html",
        "access": "scrape-and-centralize",
        "maintenance": "active",
        "license": "Gallup",
        "presentation": "Annual February Gallup news releases.",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "America's Public Enemy Number One: The dramatic rise to 51% in 2018 during the ICBM crisis and its subsequent eclipse by China and Russia.",
        "value": 4,
        "verified": True,
        "notes": "Verified from Gallup historical enemy rankings. In Feb 2018, more than half of all Americans named North Korea as the single greatest threat to the US."
    },
    {
        "id": "dprk-diplomatic-missions-abroad",
        "title": "North Korean Active Resident Diplomatic Posts Worldwide (1975-2025)",
        "publisher": "Lowy Institute Global Diplomacy Index / ROK Ministry of Foreign Affairs (MOFA)",
        "url": "https://globaldiplomacyindex.lowyinstitute.org/",
        "pull": "https://raw.githubusercontent.com/free-north-korea/data/main/samples/society/international_opinion_diplomacy.json",
        "language": "en",
        "unit": "diplomatic posts (embassies, consulates, permanent missions)",
        "frequency": "irregular",
        "coverage_start": 1975,
        "coverage_end": 2025,
        "latest_value": "2024/2025: 43-44 posts (39-40 embassies, 1 consulate, 3 UN missions); down from 53 in early 2023 (peak was 82 in 1985)",
        "geo": "national",
        "compare": "South Korea (160+ diplomatic posts), Lowy Global Diplomacy Index global rank (PRK ranks 58th)",
        "format": "json-api",
        "access": "scrape-and-centralize",
        "maintenance": "sporadic",
        "license": "Public institutional data",
        "presentation": "Lowy interactive map and ROK MOFA Diplomatic White Papers. Captures the severe contraction in late 2023 when Pyongyang shut embassies across Africa, Europe, and Asia due to financial strain.",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "Retreat from the World: North Korea's shrinking global embassy network from the 1985 Non-Aligned peak (82 posts) to the 2023 closure wave (43 posts).",
        "value": 5,
        "verified": True,
        "notes": "Verified against Lowy 2024 Index and ROK MOU records. Closures in late 2023 confirmed in Angola, Uganda, Spain, Nepal, Bangladesh, Senegal, Guinea, DR Congo, and Hong Kong."
    },
    {
        "id": "pyongyang-resident-foreign-embassies",
        "title": "Resident Foreign Embassies Inside Pyongyang Over Time",
        "publisher": "ROK Ministry of Foreign Affairs / NK News / Diplomatic Records",
        "url": "https://www.mofa.go.kr/",
        "pull": "https://raw.githubusercontent.com/free-north-korea/data/main/samples/society/international_opinion_diplomacy.json",
        "language": "en",
        "unit": "resident embassies",
        "frequency": "irregular",
        "coverage_start": 1990,
        "coverage_end": 2025,
        "latest_value": "2024/2025: ~10 resident embassies active (slow reopening by Russia, China, Nicaragua, Mongolia, Sweden); fell to ~9 in 2021 from 25 pre-COVID",
        "geo": "point",
        "compare": "Resident embassies in Seoul (>115 resident embassies)",
        "format": "html",
        "access": "scrape-and-centralize",
        "maintenance": "sporadic",
        "license": "Public record",
        "presentation": "Scattered across diplomatic reporting and think-tank tracker articles.",
        "opportunity": "scrape-and-centralize",
        "chart_idea": "The Emptied Capital: Resident foreign diplomatic presence inside Pyongyang before COVID, the 2020-2021 total Western exodus, and the slow autocratic return.",
        "value": 4,
        "verified": True,
        "notes": "Pre-pandemic Pyongyang hosted 25 embassies including Germany, UK, Sweden, Poland, Czechia, Bulgaria, Romania, India, Nigeria. All Western personnel evacuated by mid-2021 due to total border closure."
    }
]

def build_json():
    print(f"Building society.json with {len(SERIES)} series...")
    for idx, s in enumerate(SERIES):
        for k in REQUIRED_KEYS:
            if k not in s:
                raise ValueError(f"Series {s.get('id', idx)} missing required key: {k}")
    
    out_path = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../society.json"))
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(SERIES, f, indent=2, ensure_ascii=False)
    print(f"Successfully generated {out_path} ({len(SERIES)} series).")

if __name__ == "__main__":
    build_json()
