/**
 * Reading, watching and source list. Links go to a stable public page (Open Library, Wikipedia,
 * the publisher or the archive itself) rather than a store.
 */

export type ShelfId = 'memoir' | 'nonfiction' | 'film' | 'report' | 'regime' | 'data';

export interface Item {
  title: string;
  by: string;
  year?: number;
  url: string;
  note: string;
  /** Short honest caveat when an account has been challenged. */
  caveat?: string;
}

export const SHELVES: { id: ShelfId; title: string; intro: string; items: Item[] }[] = [
  {
    id: 'memoir',
    title: 'Escapee memoirs',
    intro: 'First-hand accounts. Start here.',
    items: [
      {
        title: 'The Aquariums of Pyongyang',
        by: 'Kang Chol-hwan & Pierre Rigoulot',
        year: 2000,
        url: 'https://openlibrary.org/search?q=The+Aquariums+of+Pyongyang',
        note: 'Sent to the Yodok prison camp at age 9 with his whole family. The book that put the camps on the map for many readers.',
      },
      {
        title: 'The Girl with Seven Names',
        by: 'Hyeonseo Lee',
        year: 2015,
        url: 'https://openlibrary.org/search?q=The+Girl+with+Seven+Names',
        note: 'Left at 17, lived under false identities in China for a decade, then went back to the border to bring her family out.',
      },
      {
        title: 'Escape from Camp 14',
        by: 'Blaine Harden',
        year: 2012,
        url: 'https://openlibrary.org/search?q=Escape+from+Camp+14',
        note: 'Shin Dong-hyuk’s account of being born inside a political prison camp.',
        caveat: 'Shin later revised parts of his story (2015). The core account matches other testimony.',
      },
      {
        title: 'In Order to Live',
        by: 'Yeonmi Park',
        year: 2015,
        url: 'https://openlibrary.org/search?q=In+Order+to+Live+Yeonmi+Park',
        note: 'Escape at 13 through China, trafficking, and the Gobi desert crossing to Mongolia.',
        caveat: 'Some details have been questioned by journalists and other escapees.',
      },
      {
        title: 'A River in Darkness',
        by: 'Masaji Ishikawa',
        year: 2017,
        url: 'https://openlibrary.org/search?q=A+River+in+Darkness',
        note: 'A half-Japanese man whose family moved to North Korea in 1960 on a repatriation program and spent 36 years there.',
      },
      {
        title: 'Every Falling Star',
        by: 'Sungju Lee & Susan McClelland',
        year: 2016,
        url: 'https://openlibrary.org/search?q=Every+Falling+Star+Sungju+Lee',
        note: 'From a Pyongyang childhood to living in a street gang during the famine.',
      },
      {
        title: 'Dear Leader',
        by: 'Jang Jin-sung',
        year: 2014,
        url: 'https://openlibrary.org/search?q=Dear+Leader+Jang+Jin-sung',
        note: 'A former poet laureate inside the regime’s propaganda apparatus. Rare view from the elite.',
      },
      {
        title: 'The Tears of My Soul',
        by: 'Kim Hyun-hee',
        year: 1993,
        url: 'https://openlibrary.org/search?q=The+Tears+of+My+Soul+Kim+Hyun-hee',
        note: 'Account of the 1987 KAL 858 bombing by the former DPRK intelligence operative who carried it out. Details elite recruitment, espionage training, and defection.',
      },
      {
        title: 'A Thousand Miles to Freedom',
        by: 'Eunsun Kim & Sébastien Falletti',
        year: 2015,
        url: 'https://openlibrary.org/search?q=A+Thousand+Miles+to+Freedom+Eunsun+Kim',
        note: 'Escaped with her mother during the famine and survived nine years in hiding across China before reaching South Korea through the Gobi Desert.',
      },
      {
        title: 'Under the Same Sky',
        by: 'Joseph Kim & Stephan Talty',
        year: 2015,
        url: 'https://openlibrary.org/search?q=Under+the+Same+Sky+Joseph+Kim',
        note: 'Orphaned street child (kotjebi) during the 1990s famine who survived scavenging and coal mining before escaping to the US via LiNK.',
      },
      {
        title: 'This Is Paradise! My North Korean Childhood',
        by: 'Hyok Kang & Philippe Grangereau',
        year: 2005,
        url: 'https://openlibrary.org/search?q=This+Is+Paradise+Hyok+Kang',
        note: 'Childhood in Onsong County near the Chinese border during the famine, illustrated with Kang’s own drawings of public executions and village life.',
      },
      {
        title: 'Stars Between the Sun and Moon',
        by: 'Lucia Jang & Susan McClelland',
        year: 2015,
        url: 'https://openlibrary.org/search?q=Stars+Between+the+Sun+and+Moon+Lucia+Jang',
        note: 'Surviving domestic violence, human trafficking in China, forced repatriation to North Korean labor camps, and escaping again.',
      },
      {
        title: 'The Hard Road Out: One Woman’s Escape from North Korea',
        by: 'Jihyun Park & Seh-lynn Chai',
        year: 2023,
        url: 'https://openlibrary.org/search?q=The+Hard+Road+Out+Jihyun+Park',
        note: 'Sold into forced marriage in rural China, repatriated to a forced-labor camp in Chongjin, survived, and escaped again to become a human rights campaigner in the UK.',
      },
      {
        title: 'Eyes of the Tailless Animals: Prison Memoirs of a North Korean Woman',
        by: 'Soon Ok Lee',
        year: 1999,
        url: 'https://openlibrary.org/search?q=Eyes+of+the+Tailless+Animals+Soon+Ok+Lee',
        note: 'Former state distribution supervisor imprisoned in Kyohwaso No. 1 (Kaechon) for six years. One of the earliest testimonies on ordinary penal camps.',
        caveat: 'Some specific torture claims differ from descriptions by later defectors, but general camp conditions match.',
      },
      {
        title: 'Long Road Home: Testimony of a North Korean Camp Survivor',
        by: 'Kim Yong & Kim Suk-young',
        year: 2009,
        url: 'https://openlibrary.org/search?q=Long+Road+Home+Kim+Yong',
        note: 'Former lieutenant colonel in the Ministry of Public Security sent to Camp 14 and Camp 18 after his father’s past was discovered; the only known survivor to escape both.',
      },
    ],
  },
  {
    id: 'nonfiction',
    title: 'Understanding the country',
    intro: 'Journalism and analysis that explain how North Korea actually works.',
    items: [
      {
        title: 'Nothing to Envy',
        by: 'Barbara Demick',
        year: 2009,
        url: 'https://openlibrary.org/search?q=Nothing+to+Envy+Demick',
        note: 'Six people from the city of Chongjin through the 1990s famine. The best single book on ordinary life.',
      },
      {
        title: 'The Real North Korea',
        by: 'Andrei Lankov',
        year: 2013,
        url: 'https://openlibrary.org/search?q=The+Real+North+Korea+Lankov',
        note: 'Why the regime survives and how it might change. Lankov studied in Pyongyang in the 1980s.',
      },
      {
        title: 'North Korea Confidential',
        by: 'Daniel Tudor & James Pearson',
        year: 2015,
        url: 'https://openlibrary.org/search?q=North+Korea+Confidential',
        note: 'Markets, smuggling, fashion, drugs and media. How people actually get by.',
      },
      {
        title: 'The Great Successor',
        by: 'Anna Fifield',
        year: 2019,
        url: 'https://openlibrary.org/search?q=The+Great+Successor+Fifield',
        note: 'Biography of Kim Jong Un.',
      },
      {
        title: 'The Cleanest Race',
        by: 'B. R. Myers',
        year: 2010,
        url: 'https://openlibrary.org/search?q=The+Cleanest+Race+Myers',
        note: 'Argues the regime’s real ideology is race-based nationalism, not communism. Changes how you read the propaganda.',
      },
      {
        title: 'Without You, There Is No Us',
        by: 'Suki Kim',
        year: 2014,
        url: 'https://openlibrary.org/search?q=Without+You+There+Is+No+Us',
        note: 'Undercover as a teacher to the sons of the elite at a Pyongyang university.',
      },
      {
        title: 'The Accusation',
        by: 'Bandi (pseudonym)',
        year: 2017,
        url: 'https://openlibrary.org/search?q=The+Accusation+Bandi',
        note: 'Short stories written by a writer still living inside North Korea, smuggled out. Fiction, but rare.',
      },
      {
        title: 'The Impossible State',
        by: 'Victor Cha',
        year: 2012,
        url: 'https://openlibrary.org/search?q=The+Impossible+State+Victor+Cha',
        note: 'Policy view from a former White House North Korea adviser.',
      },
      {
        title: 'Under the Loving Care of the Fatherly Leader',
        by: 'Bradley K. Martin',
        year: 2004,
        url: 'https://openlibrary.org/search?q=Under+the+Loving+Care+of+the+Fatherly+Leader',
        note: 'Monumental 800-page history of the Kim dynasty based on four decades of reporting and hundreds of defector interviews.',
      },
      {
        title: 'North of the DMZ: Essays on Daily Life in North Korea',
        by: 'Andrei Lankov',
        year: 2007,
        url: 'https://openlibrary.org/search?q=North+of+the+DMZ+Lankov',
        note: 'Short, concrete essays on everyday social reality: travel passes, house searches, smuggled radios, fashion, and food rations.',
      },
      {
        title: 'The Sister: The extraordinary story of Kim Yo Jong',
        by: 'Sung-Yoon Lee',
        year: 2023,
        url: 'https://openlibrary.org/search?q=The+Sister+Sung-Yoon+Lee',
        note: 'Detailed biography and political analysis of Kim Yo Jong, sister to Kim Jong Un and de facto deputy leader of the regime.',
      },
      {
        title: 'The Invitation-Only Zone',
        by: 'Robert S. Boynton',
        year: 2016,
        url: 'https://openlibrary.org/search?q=The+Invitation-Only+Zone+Boynton',
        note: 'Investigation into North Korea’s abduction of Japanese citizens from coastal beaches in the 1970s and 1980s to train espionage operatives.',
      },
      {
        title: 'Escape from North Korea: The Untold Story of Asia’s Underground Railroad',
        by: 'Melanie Kirkpatrick',
        year: 2012,
        url: 'https://openlibrary.org/search?q=Escape+from+North+Korea+Melanie+Kirkpatrick',
        note: 'The network of Christian missionaries, brokers, and safe houses guiding defectors along the 3,000-mile route across China and Southeast Asia.',
      },
      {
        title: 'The Lazarus Heist',
        by: 'Geoff White',
        year: 2022,
        url: 'https://openlibrary.org/search?q=The+Lazarus+Heist+Geoff+White',
        note: 'How North Korea’s Reconnaissance General Bureau cyber army grew from the 2014 Sony hack to billion-dollar cryptocurrency and central bank heists.',
      },
      {
        title: 'North Korea: State of Paranoia',
        by: 'Paul French',
        year: 2014,
        url: 'https://openlibrary.org/search?q=North+Korea+State+of+Paranoia+Paul+French',
        note: 'Comprehensive overview of political economics, military doctrine, and how the regime adapted to survive the post-Cold War era.',
      },
      {
        title: 'North Korea: Markets and Military Rule',
        by: 'Hazel Smith',
        year: 2015,
        url: 'https://openlibrary.org/search?q=North+Korea+Markets+and+Military+Rule',
        note: 'Detailed economic analysis of how the breakdown of the public distribution system triggered bottom-up marketization across North Korean society.',
      },
    ],
  },
  {
    id: 'film',
    title: 'Documentaries',
    intro: 'If you only watch one, watch Beyond Utopia.',
    items: [
      {
        title: 'Beyond Utopia',
        by: 'Madeleine Gavin',
        year: 2023,
        url: 'https://en.wikipedia.org/wiki/Beyond_Utopia',
        note: 'Follows a real escape through China, Vietnam, Laos and Thailand, filmed as it happens.',
      },
      {
        title: 'Under the Sun',
        by: 'Vitaly Mansky',
        year: 2015,
        url: 'https://en.wikipedia.org/wiki/Under_the_Sun_(2015_film)',
        note: 'A state-approved documentary about a Pyongyang family, with the regime’s staging left in.',
      },
      {
        title: 'The Mole: Undercover in North Korea',
        by: 'Mads Brügger',
        year: 2020,
        url: 'https://en.wikipedia.org/wiki/The_Mole:_Undercover_in_North_Korea',
        note: 'A Danish chef infiltrates a pro-regime friendship group and ends up in arms deals.',
      },
      {
        title: 'The Lovers and the Despot',
        by: 'Robert Cannan & Ross Adam',
        year: 2016,
        url: 'https://en.wikipedia.org/wiki/The_Lovers_and_the_Despot',
        note: 'Kim Jong Il kidnapped a South Korean director and actress to make films for him.',
      },
      {
        title: 'Crossing the Line',
        by: 'Daniel Gordon',
        year: 2006,
        url: 'https://en.wikipedia.org/wiki/Crossing_the_Line_(2006_film)',
        note: 'A US soldier who defected to North Korea in 1962 and lived there for decades.',
      },
      {
        title: 'Camp 14: Total Control Zone',
        by: 'Marc Wiese',
        year: 2012,
        url: 'https://en.wikipedia.org/wiki/Camp_14:_Total_Control_Zone',
        note: 'Features testimony from Shin Dong-hyuk alongside rare interviews with former prison camp guards and security officials.',
      },
      {
        title: 'Shadow Flowers',
        by: 'Wang Seung-yong',
        year: 2019,
        url: 'https://en.wikipedia.org/wiki/Shadow_Flowers',
        note: 'Follows Ryun-hee Kim, a Pyongyang housewife who arrived unintentionally in South Korea and spent a decade campaigning to return home.',
      },
      {
        title: 'Children of the Secret State',
        by: 'Hardcash Productions',
        year: 2000,
        url: 'https://en.wikipedia.org/wiki/Children_of_the_Secret_State',
        note: 'Undercover footage of starving street children during the 1990s famine that first forced international recognition of the crisis.',
      },
      {
        title: 'A State of Mind',
        by: 'Daniel Gordon',
        year: 2004,
        url: 'https://en.wikipedia.org/wiki/A_State_of_Mind',
        note: 'Follows two Pyongyang schoolgirls training for months to perform in the Arirang Mass Games, showing everyday life inside the capital.',
      },
      {
        title: 'Seoul Train',
        by: 'Jim Butterworth, Lisa Sleeth & Aaron Lubarsky',
        year: 2004,
        url: 'https://en.wikipedia.org/wiki/Seoul_Train',
        note: 'Documents the underground railroad across China and the severe risks of arrest and forced repatriation by Chinese authorities.',
      },
      {
        title: 'I Am Sun Mu',
        by: 'Adam Sjoberg',
        year: 2015,
        url: 'https://en.wikipedia.org/wiki/I_Am_Sun_Mu',
        note: 'A former North Korean state propaganda painter defected to Seoul and creates subversive political art, mounting a covert exhibition in Beijing.',
      },
      {
        title: 'Secret State of North Korea',
        by: 'PBS Frontline',
        year: 2014,
        url: 'https://www.pbs.org/wgbh/frontline/documentary/secret-state-of-north-korea/',
        note: 'Smuggled footage inside North Korea reveals illegal DVDs, cell phones, black market transactions, and quiet pushback against state controls.',
      },
    ],
  },
  {
    id: 'report',
    title: 'Key reports',
    intro: 'The primary documents most articles cite.',
    items: [
      {
        title: 'Report of the UN Commission of Inquiry on Human Rights in the DPRK',
        by: 'United Nations',
        year: 2014,
        url: 'https://www.ohchr.org/en/hr-bodies/hrc/co-idprk/commission-inquiry-on-h-rin-dprk',
        note: 'Found crimes against humanity "without any parallel in the contemporary world". Still the baseline.',
      },
      {
        title: 'UN OHCHR report on the decade since the Commission of Inquiry',
        by: 'United Nations',
        year: 2025,
        url: 'https://www.hrw.org/news/2025/09/16/north-korea-lost-decade-of-rights-abuses',
        note: 'Over 300 interviews. Found more surveillance, forced labor and executions since 2014.',
      },
      {
        title: 'The Hidden Gulag (2nd ed.)',
        by: 'David Hawk, HRNK',
        year: 2012,
        url: 'https://www.hrnk.org/publications/hrnk-publications.php',
        note: 'Camp by camp, with satellite imagery and testimony.',
      },
      {
        title: 'World Report 2026: North Korea',
        by: 'Human Rights Watch',
        year: 2026,
        url: 'https://www.hrw.org/world-report/2026/country-chapters/north-korea',
        note: 'Short annual summary of what changed.',
      },
      {
        title: 'SIPRI Yearbook 2026: World nuclear forces',
        by: 'SIPRI',
        year: 2026,
        url: 'https://www.sipri.org/sites/default/files/YB26%2008%20World%20Nuclear%20Forces.pdf',
        note: 'Current estimate of North Korea’s warheads (about 60) and fissile material.',
      },
      {
        title: 'Parallel Gulag: North Korea’s "An-jeon-bu" Police Detention Facilities',
        by: 'David Hawk & Amanda Mortwedt Oh, HRNK',
        year: 2017,
        url: 'https://www.hrnk.org/publications/hrnk-publications.php',
        note: 'Satellite imagery and defector testimony mapping the ordinary police holding centres and labour training camps across the country.',
      },
      {
        title: 'White Paper on Human Rights in North Korea',
        by: 'Korea Institute for National Unification (KINU)',
        year: 2024,
        url: 'https://www.kinu.or.kr/eng/module/report/list.do?cid=greport',
        note: 'Comprehensive annual report by South Korea’s state research institute, based on hundreds of recent in-depth escapee interviews.',
      },
      {
        title: 'Denied from the Start: Human Rights Violations Against Women',
        by: 'Korea Future',
        year: 2023,
        url: 'https://koreafuture.org/reports/denied-from-the-start',
        note: 'Detailed forensic documentation of gender-based abuses, forced labour, and sexual violence in state detention facilities.',
      },
      {
        title: 'Captured on Camera: North Korea’s Controlled Border Infrastructure',
        by: 'Human Rights Watch',
        year: 2024,
        url: 'https://www.hrw.org/report/2024/03/07/captured-camera/north-koreas-controlled-border-infrastructure-2019-2023',
        note: 'Satellite imagery documenting how 500+ km of newly erected double-fences, guard posts, and shoot-on-sight orders crushed escape routes since 2020.',
      },
      {
        title: 'Final Report of the UN Panel of Experts on DPRK Sanctions',
        by: 'United Nations Security Council',
        year: 2024,
        url: 'https://www.undocs.org/S/2024/171',
        note: 'The final investigative report on sanctions evasion, maritime ship-to-ship transfers, and arms deals before the Russian veto ended the mandate.',
      },
      {
        title: 'North Korea’s Digital Gulag: Surveillance and the Technology of Repression',
        by: 'Martyn Williams & Natalia Slavney, Stimson / 38 North',
        year: 2024,
        url: 'https://www.stimson.org/2024/north-koreas-digital-gulag/',
        note: 'Technical analysis of smartphone watermarks, software controls, and automated file inspection used to block external information.',
      },
    ],
  },
  {
    id: 'regime',
    title: 'From the regime itself',
    intro: 'Primary sources published by North Korea. Read them to understand the propaganda, not to believe it.',
    items: [
      {
        title: 'KCNA Watch',
        by: 'NK News',
        url: 'https://kcnawatch.org',
        note: 'Searchable archive of KCNA, Rodong Sinmun and other state media, without visiting North Korean servers.',
      },
      {
        title: 'Foreign Languages Publishing House books',
        by: 'Internet Archive',
        url: 'https://archive.org/search?query=%22Foreign+Languages+Publishing+House%22+Pyongyang',
        note: 'Scanned propaganda books, leader biographies and Juche texts in English.',
      },
      {
        title: 'North Korea Collection',
        by: 'University of Hawaiʻi at Mānoa Library',
        url: 'https://guides.library.manoa.hawaii.edu/kstudies/northkoreanbooks',
        note: 'Thousands of North Korean books and journals, with catalog records.',
      },
      {
        title: 'North Korea in the World',
        by: 'East-West Center & NCNK',
        url: 'https://www.northkoreaintheworld.org',
        note: 'Data on North Korea’s trade, diplomacy and foreign ties.',
      },
    ],
  },
  {
    id: 'data',
    title: 'Data and OSINT tools',
    intro: 'For researchers and developers who want to build on this.',
    items: [
      {
        title: 'DPRK Digital Atlas',
        by: '38 North / Stimson',
        url: 'https://www.stimson.org/project/38-north/dprk-digital-atlas/',
        note: 'Geospatial dataset of political, economic and security sites.',
      },
      {
        title: 'North Korean Prison Database',
        by: 'NKDB',
        url: 'https://nkpd.org',
        note: 'Detention facilities and cases from escapee testimony.',
      },
      {
        title: 'OCCRP Aleph',
        by: 'OCCRP',
        url: 'https://aleph.occrp.org',
        note: 'Searchable leaks and records, including sanctions-evasion company networks.',
      },
      {
        title: 'OSINT Tools: North Korea',
        by: 'paulpogoda',
        url: 'https://github.com/paulpogoda/OSINT-Tools-North-Korea',
        note: 'Curated list of maps, datasets and tools.',
      },
      {
        title: 'CNS North Korea Missile Test Database',
        by: 'James Martin CNS / NTI',
        url: 'https://www.nti.org/analysis/articles/cns-north-korea-missile-test-database/',
        note: 'The data behind our missile test map.',
      },
      {
        title: 'nk-missile-tests',
        by: 'nagix',
        url: 'https://github.com/nagix/nk-missile-tests',
        note: 'Original open-source visualization our missile map is based on. Updated as new tests happen.',
      },
      {
        title: 'NK Pro',
        by: 'Korea Risk Group',
        url: 'https://www.nknews.org/pro/',
        note: 'Intelligence service providing commercial satellite imagery analysis, aviation tracking, trade vessel data, and leadership movement registries.',
      },
      {
        title: 'Daily NK Market Prices',
        by: 'Daily NK',
        url: 'https://www.dailynk.com/english/market-price/',
        note: 'Bi-weekly commodity and foreign exchange price tracker compiled from anonymous contacts inside North Korean markets.',
      },
      {
        title: 'KPA Journal',
        by: 'Joseph S. Bermudez Jr.',
        url: 'http://www.kpajournal.com',
        note: 'Specialized monographs on the Korean People’s Army, coastal artillery, special operations command, and hardened artillery sites.',
      },
    ],
  },
];
